services: 

  shell:
    build:
      context: .
      dockerfile: ./docker_files/dev/server.Dockerfile
    command: bash -c "python shell.py"
    volumes:
      - ./server:/server
    stdin_open: true
    tty: true
    environment:
      - DATASTORE_DATASET=test-dev
      - DATASTORE_EMULATOR_HOST=localhost:8081
      - DATASTORE_EMULATOR_HOST_PATH=localhost:8081/datastore
      - DATASTORE_HOST=http://localhost:8081
      - DATASTORE_PROJECT_ID=test-dev
      - DATASTORE_PORT=8081
      - ORM_CLIENT=core.orm.clients.datastore.DatastoreClient

