services: 

  test-app-server:
    build:
      context: .
      dockerfile: ./docker_files/test.Dockerfile
    volumes:
      - ./server:/server
    ports:
      - "8088:8088"
    stdin_open: true
    tty: true
    environment:
      - ENV=test
    env_file:
      - .env

  test-server:
    build:
      context: .
      dockerfile: ./docker_files/test.Dockerfile
    command: bash -c "python wait_for_it.py test-app-server 8088 && python -m unittest discover && python shell.py"
    volumes:
      - ./server:/server
    stdin_open: true
    tty: true
    environment:
      - ENV=test
      - BASE_URL=http://test-app-server:8088
    env_file:
      - .env
    depends_on:
      - test-app-server

